#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'caesarCipher' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING s
#  2. INTEGER k
#

def caesarCipher(s, k):
    newstring = ""
    for letter in s:
        if letter.isalpha():
            num = ord("A") if letter.isupper() else ord('a')
            newstring += chr((ord(letter) - num + k) % 26 + num)
        else:
            newstring += letter
    return newstring

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    s = input()

    k = int(input().strip())

    result = caesarCipher(s, k)

    fptr.write(result + '\n')

    fptr.close()
