#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'counterGame' function below.
#
# The function is expected to return a STRING.
# The function accepts LONG_INTEGER n as parameter.
#

def counterGame(n):
    people = ["Louise", "Richard"]
    count = 0
    sum = n
    while sum != 1:
        modulus = sum - 2 ** (math.log(sum)//math.log(2))
        if modulus != 0:
            sum =modulus
        else:
            sum = sum/2
        if sum != 1:
            count+=1
    return people[count % 2]
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        result = counterGame(n)

        fptr.write(result + '\n')

    fptr.close()
