#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'dynamicArray' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER n
#  2. 2D_INTEGER_ARRAY queries
#

def dynamicArray(n, queries):
    arr = [[] for i in range(n)]
    lastAnswer = 0
    results = []

    for query in queries:
        query_type, x, y = query

        if query_type == 1:
            arrIndex = (x ^ lastAnswer) % n
            arr[arrIndex].append(y)
        elif query_type == 2:
            arrIndex = (x ^ lastAnswer) % n
            lastAnswer = arr[arrIndex][y % len(arr[arrIndex])]
            results.append(lastAnswer)

    return results

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    q = int(first_multiple_input[1])

    queries = []

    for _ in range(q):
        queries.append(list(map(int, input().rstrip().split())))

    result = dynamicArray(n, queries)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
