#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'equalStacks' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY h1
#  2. INTEGER_ARRAY h2
#  3. INTEGER_ARRAY h3
#

def equalStacks(h1, h2, h3):
    
    h1.reverse()
    h2.reverse()
    h3.reverse()

    
    sum_h1 = [0] * (len(h1) + 1)
    sum_h2 = [0] * (len(h2) + 1)
    sum_h3 = [0] * (len(h3) + 1)

    for i in range(1, len(h1) + 1):
        sum_h1[i] = sum_h1[i - 1] + h1[i - 1]

    for i in range(1, len(h2) + 1):
        sum_h2[i] = sum_h2[i - 1] + h2[i - 1]

    for i in range(1, len(h3) + 1):
        sum_h3[i] = sum_h3[i - 1] + h3[i - 1]

    for height in reversed(sum_h1):
        if height in sum_h2 and height in sum_h3:
            return height

    return 0

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n1 = int(first_multiple_input[0])

    n2 = int(first_multiple_input[1])

    n3 = int(first_multiple_input[2])

    h1 = list(map(int, input().rstrip().split()))

    h2 = list(map(int, input().rstrip().split()))

    h3 = list(map(int, input().rstrip().split()))

    result = equalStacks(h1, h2, h3)

    fptr.write(str(result) + '\n')

    fptr.close()
