#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    arr.sort()
    sumUp = 0
    sumDown = 0
    for i in range(len(arr) - 1):
        sumUp += arr[i]
    arr.sort(reverse=True)
    for i in range(len(arr) - 1):
        sumDown += arr[i]
    print(str(sumUp) + " " + str(sumDown))

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
