#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    length = 0
    positives = 0
    negatives = 0
    zeros = 0
    for i in arr:
        if (i > 0):
            positives += 1
        if (i < 0):
            negatives += 1
        if (i == 0):
            zeros += 1
        length += 1
    print("{:.6f}".format(positives/length))
    print("{:.6f}".format(negatives/length))
    print("{:.6f}".format(zeros/length))
    return

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
