#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'isValid' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def isValid(s):
    newdict = {}
    for letter in s:
        if letter in newdict:
            newdict[letter] += 1
        else:
            newdict[letter] = 1
    numValues = []
    for value in newdict.values():
        numValues.append(value)
    counter = 0
    changes = 0
    counter = numValues[0]
    for i in range(1, len(numValues)):
        if numValues[i] != counter:
            changes+= 1
    if changes <= 1:
        return "YES"
    else:
        return "NO"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = isValid(s)

    fptr.write(result + '\n')

    fptr.close()
