#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    hours = int(s[:2])
    amPM = s[-2:]
    if amPM == "AM" and hours == 12:
        time = "00" + s[2:-2]
    elif amPM == "PM" and hours != 12:
        time = str(hours + 12) + s[2:-2]
    else:
        time = s[:8]
    return time
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
