#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'hackerlandRadioTransmitters' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY x
#  2. INTEGER k
#

def hackerlandRadioTransmitters(x, k):
    x.sort()  # Sort the house locations in ascending order
    n = len(x)
    transmitters = 0
    i = 0

    while i < n:
        transmitters += 1
        location = x[i] + k

        # Move to the rightmost house within the current transmitter's range
        while i < n and x[i] <= location:
            i += 1

        # Move to the rightmost house outside the current transmitter's range
        i -= 1
        location = x[i] + k

        # Move to the rightmost house outside the next potential transmitter's range
        while i < n and x[i] <= location:
            i += 1

    return transmitters

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    x = list(map(int, input().rstrip().split()))

    result = hackerlandRadioTransmitters(x, k)

    fptr.write(str(result) + '\n')

    fptr.close()
